import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Container from "react-bootstrap/Container";
import Nav from "react-bootstrap/Nav";
import Navbar from "react-bootstrap/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="navbar navbar-expand-lg bg-body-tertiary">
          <div className="container-fluid d-flex justify-content-between">
            <h1>
              <a className="navbar-brand" href="#">
                Web
              </a>
            </h1>
            <ul className="nav d-flex">
              <li className="nav-item">
                <a className="nav-link" aria-current="page" href="#">
                  html
                </a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#">
                  css
                </a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#">
                  javascript
                </a>
              </li>
            </ul>
          </div>
        </nav>
      </body>
    </html>
  );
}
